// EmotionClassifier.swift
// Wraps the auto-generated EmotionClassifier CoreML class.
//
// XCODE BUILD FIX NOTES:
// ─────────────────────────────────────────────────────────────────────────
// 1. The `EmotionClassifier` class on line below is AUTO-GENERATED by Xcode
//    when you drag EmotionClassifier.mlmodel into the project. Do NOT write
//    your own MLFeatureProvider — use only the generated class.
//
// 2. The prediction method parameter name (e.g. `input_1`) comes from the
//    CoreML model's input spec. Run convert_coreml.py and note the printed
//    spec input name. If it differs from 'input_1', update the prediction
//    call in classify() below accordingly.
//
// 3. CVPixelBuffer format from AVFoundation is kCVPixelFormatType_32BGRA.
//    CIImage handles BGRA->RGB conversion transparently when rendering to
//    a new BGRA buffer — no manual channel swapping is needed.
//
// Reference: Gursesli et al., IEEE Access 2024, DOI:10.1109/ACCESS.2024.3380847

import CoreML
import CoreImage
import Vision

class EmotionClassifierWrapper {

    // The 'EmotionClassifier' identifier below is auto-generated by Xcode
    // from EmotionClassifier.mlmodel. Build the project once to generate it.
    private var model: EmotionClassifier?

    // MARK: - Smoothing & Stability

    // Key: "cx_cy" string derived from face center (1 decimal), value: ring buffer of score dicts
    private var smoothingBuffers:  [String: [[Emotion: Float]]] = [:]
    // Key: "cx_cy", value: (current dominant emotion, consecutive frame count)
    private var stabilityTrackers: [String: (emotion: Emotion, count: Int)] = [:]

    private let smoothingWindowSize = 5   // frames to average
    private let stabilityThreshold  = 3   // consecutive frames before committing
    private let confidenceThreshold: Float = 0.40  // minimum confidence to display

    // MARK: - Initialization

    init() {
        let config = MLModelConfiguration()
        config.computeUnits = .all   // use ANE + GPU + CPU
        do {
            self.model = try EmotionClassifier(configuration: config)
        } catch {
            print("ERROR: Failed to load EmotionClassifier.mlmodel — \(error)")
            self.model = nil
        }
    }

    // MARK: - Main classify entry point

    func classify(
        pixelBuffer: CVPixelBuffer,
        face: DetectedFace,
        imageSize: CGSize
    ) -> EmotionResult? {
        guard let model = self.model else { return nil }

        // 1. Crop face region from full-frame buffer
        guard let cropped = cropPixelBuffer(
            pixelBuffer, toRect: face.pixelRect, imageSize: imageSize
        ) else { return nil }

        // 2. Resize to 96×96 (model input size)
        guard let resized = resizePixelBuffer(
            cropped, toSize: CGSize(width: 96, height: 96)
        ) else { return nil }

        // 3. Run inference via auto-generated class
        //    NOTE: If Xcode shows a different parameter name than 'input_1',
        //    update the parameter label below to match.
        guard let output = try? model.prediction(input_1: resized) else {
            return nil
        }

        // 4. Parse class probabilities from CoreML output dict
        let probs = output.classLabelProbs
        var scores: [Emotion: Float] = [:]
        for emotion in Emotion.allCases {
            scores[emotion] = Float(probs[emotion.rawValue] ?? 0.0)
        }

        // 5. Apply moving average smoothing (reduces flicker)
        let key = faceKey(face)
        var buffer = smoothingBuffers[key] ?? []
        buffer.append(scores)
        if buffer.count > smoothingWindowSize { buffer.removeFirst() }
        smoothingBuffers[key] = buffer

        let averaged = averageScores(buffer)

        // 6. Get top emotion and check confidence threshold
        guard let top = averaged.max(by: { $0.value < $1.value }),
              top.value >= confidenceThreshold else { return nil }

        // 7. Stability gate: only commit after N consecutive same-emotion frames
        var tracker = stabilityTrackers[key] ?? (emotion: top.key, count: 0)
        if tracker.emotion == top.key {
            tracker.count += 1
        } else {
            tracker = (emotion: top.key, count: 1)
        }
        stabilityTrackers[key] = tracker
        guard tracker.count >= stabilityThreshold else { return nil }

        return EmotionResult(
            emotion:    top.key,
            confidence: top.value,
            allScores:  averaged,
            faceIndex:  face.index
        )
    }

    // MARK: - Private Helpers

    /// Stable string key for a face based on its normalised center position.
    private func faceKey(_ face: DetectedFace) -> String {
        let cx = (face.boundingBox.midX * 10).rounded() / 10
        let cy = (face.boundingBox.midY * 10).rounded() / 10
        return "\(cx)_\(cy)"
    }

    /// Element-wise average of a ring buffer of score dictionaries.
    private func averageScores(_ buffer: [[Emotion: Float]]) -> [Emotion: Float] {
        var summed: [Emotion: Float] = [:]
        for scores in buffer {
            for (emotion, score) in scores {
                summed[emotion, default: 0] += score
            }
        }
        let n = Float(buffer.count)
        return summed.mapValues { $0 / n }
    }

    // MARK: - Pixel Buffer Utilities

    /// Crop a CVPixelBuffer to a pixel rect using CIImage.
    /// AVFoundation delivers BGRA; CIImage handles the format transparently.
    private func cropPixelBuffer(
        _ buffer: CVPixelBuffer,
        toRect rect: CGRect,
        imageSize: CGSize
    ) -> CVPixelBuffer? {
        let ciImage = CIImage(cvPixelBuffer: buffer)

        // Clamp crop rect to image bounds to prevent negative dimensions
        let clamped = CGRect(
            x:      max(0, rect.origin.x),
            y:      max(0, rect.origin.y),
            width:  min(rect.width,  imageSize.width  - max(0, rect.origin.x)),
            height: min(rect.height, imageSize.height - max(0, rect.origin.y))
        )
        guard clamped.width > 0, clamped.height > 0 else { return nil }

        let cropped = ciImage.cropped(to: clamped)
        return renderCIImage(cropped, size: CGSize(width: clamped.width, height: clamped.height))
    }

    /// Resize a CVPixelBuffer to target size using CIImage affine transform.
    private func resizePixelBuffer(
        _ buffer: CVPixelBuffer,
        toSize size: CGSize
    ) -> CVPixelBuffer? {
        let ciImage = CIImage(cvPixelBuffer: buffer)
        let scaleX  = size.width  / CGFloat(CVPixelBufferGetWidth(buffer))
        let scaleY  = size.height / CGFloat(CVPixelBufferGetHeight(buffer))
        let scaled  = ciImage.transformed(by: CGAffineTransform(scaleX: scaleX, y: scaleY))
        return renderCIImage(scaled, size: size)
    }

    /// Render a CIImage into a new BGRA CVPixelBuffer of the given size.
    private func renderCIImage(_ ciImage: CIImage, size: CGSize) -> CVPixelBuffer? {
        var buffer: CVPixelBuffer?
        let attrs: [String: Any] = [
            kCVPixelBufferCGImageCompatibilityKey as String: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey as String: true
        ]
        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            Int(size.width), Int(size.height),
            kCVPixelFormatType_32BGRA,
            attrs as CFDictionary,
            &buffer
        )
        guard status == kCVReturnSuccess, let out = buffer else { return nil }
        CIContext().render(ciImage, to: out)
        return out
    }
}
